### ISSUE TITLE
Visual Studio 2019 Install Failing

### ISSUE THREAD

**Issue by ToddTaylor** [OmarElabd/ObjectExporter#84]
When attempting to install the Object Exporter in Visual Studio 2019 (16.0.0 Preview 1.1), an error occurs with the following message:

`12/27/2018 2:32:30 PM - Extension cannot be installed to the following products due to missing prerequisites:
12/27/2018 2:32:30 PM - 	Microsoft Visual Studio Enterprise 2019
12/27/2018 2:32:30 PM - 		-------------------------------------------------------
12/27/2018 2:32:30 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12/27/2018 2:32:30 PM - 		Name         : Visual Studio core editor
12/27/2018 2:32:30 PM - 		Version      : [11.0,16.0)
12/27/2018 2:32:30 PM - 		Error        : The prerequisite version specified does not match the version installed
12/27/2018 2:32:30 PM - 
12/27/2018 2:32:30 PM - System.InvalidOperationException: No modifications could be applied.`

**Comment by ToddTaylor** [comment]
The fix is very simple... just some minor tweaks to the .vsixmanifest:

https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by robalexclark** [comment]
Hi - can you please provide an updated build for 2019 as I tried the fixes suggested but couldn't get it to compile.

**Comment by OmarElabd** [comment]
I will try and provide a 2019 build in the next couple of weeks.

**Comment by dharmaturtle** [comment]
Dunno if this is in bad taste, but in the meantime I've been using this, which works at runtime instead of being a plugin.

https://www.nuget.org/packages/ObjectDumper.NET/

**Comment by ibyet05** [comment]
It is not enough to change .vsixmanifest only. You should do same things for  **catalog.json** as well.

**Comment by mzhukovs** [comment]
I can't install for VS2019 either:
![image](https://user-images.githubusercontent.com/13161978/57745710-ca584a80-7700-11e9-9970-5f857fd733a8.png)

**Comment by keyle56** [comment]
Hi! Is there any update on when the extension will work "out of the box"?

**Comment by sehuff** [comment]
> The fix is very simple... just some minor tweaks to the .vsixmanifest:
> 
> https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

I updated the file - but it appears I need a license to Telerik.WinControls.dll in order to do the build?

**Comment by sehuff** [comment]
Nevermind my last comment I just had to unblock the downloaded files before the build.  However, I know have the same issue as mzhukovs - prerequisites that cannot be resolved.

**Comment by domusvita-zz** [comment]
Looks like a pull request has been pending for a little over a week that might fix this issue. Hopefully gets merged soon.  Looks like a great product.

**Comment by maxcl10** [comment]
Is there any news on this topic. When installing the extension only vs2017 is proposed.

**Comment by vurso** [comment]
Is this fixed? I tried the latest version and sadly it doesn't work in VS2019 such a shame

**Comment by ldy985** [comment]
I compiled a version using one of the pull requests: 
[ObjectExporter.zip](https://github.com/OmarElabd/ObjectExporter/files/3708957/ObjectExporter.zip) it should work fine with VS2019.

**Comment by krs4444** [comment]
> I compiled a version using one of the pull requests:
> [ObjectExporter.zip](https://github.com/OmarElabd/ObjectExporter/files/3708957/ObjectExporter.zip) it should work fine with VS2019.

Thank you, this one works on VS2019 Community Edition too!

**Comment by vurso** [comment]
> > I compiled a version using one of the pull requests:
> > [ObjectExporter.zip](https://github.com/OmarElabd/ObjectExporter/files/3708957/ObjectExporter.zip) it should work fine with VS2019.
> 
> Thank you, this one works on VS2019 Community Edition too!

Someone should fork this project (with the fixed version).

**Comment by SteGriff** [comment]
Instead of rebuilding, you can also hack the vsix:
* Change the extension from vsix to zip, and unzip it
* In both `manifest.json` and `catalog.json` find `CoreEditor` and replace that key-value pair with `"Microsoft.VisualStudio.Component.CoreEditor":"[15.0,17.0)"`
* In `extension.vsixmanifest` replace the content of the `Installation` XML node with:

```
    <InstallationTarget Version="[14.0,17.0)" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[14.0,17.0)" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[14.0,17.0)" Id="Microsoft.VisualStudio.Enterprise" />
```

Hope it helps someone :)

**Comment by breadshort** [comment]
Still can't install the extension:
error `"This extension is not installable on any currently installed products."`
Installation log:
```
09.03.2020 22:45:04 - Microsoft VSIX Installer
09.03.2020 22:45:04 - -------------------------------------------
09.03.2020 22:45:04 - Initializing Install...
09.03.2020 22:45:04 - Extension Details...
09.03.2020 22:45:04 - 	Identifier      : 07fb5b16-f4be-4488-9a19-b4f36d2c05a6
09.03.2020 22:45:04 - 	Name            : Object Exporter
09.03.2020 22:45:04 - 	Author          : Omar Elabd
09.03.2020 22:45:04 - 	Version         : 1.8.0
09.03.2020 22:45:04 - 	Description     : Object Exporter creates serializations of in memory objects from your various debugging windows. Currently supported output formats are: CSharp Object Initialization Code, JSON and XML.
09.03.2020 22:45:04 - 	Locale          : en-US
09.03.2020 22:45:04 - 	MoreInfoURL     : http://www.omarelabd.net/exporting-objects-from-the-visual-studio-debugger/
09.03.2020 22:45:04 - 	InstalledByMSI  : False
09.03.2020 22:45:04 - 	SupportedFrameworkVersionRange : [4.5,)
09.03.2020 22:45:04 - 
09.03.2020 22:45:04 - 	Supported Products : 
09.03.2020 22:45:04 - 		Microsoft.VisualStudio.Community
09.03.2020 22:45:04 - 			Version : [14.0,17.0)
09.03.2020 22:45:04 - 		Microsoft.VisualStudio.Pro
09.03.2020 22:45:04 - 			Version : [14.0,17.0)
09.03.2020 22:45:04 - 		Microsoft.VisualStudio.Enterprise
09.03.2020 22:45:04 - 			Version : [14.0,17.0)
09.03.2020 22:45:04 - 
09.03.2020 22:45:04 - 	References      : 
09.03.2020 22:45:04 - 
09.03.2020 22:45:04 - Searching for applicable products...
09.03.2020 22:45:04 - Found installed product - Global Location
09.03.2020 22:45:04 - Found installed product - AtmelStudio
09.03.2020 22:45:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by SteGriff** [comment]
> Still can't install the extension:
> error `"This extension is not installable on any currently installed products."`
> Installation log:
> *snip*

@breadshort, what version and edition of VS are you installing it into? Add the version numbers and editions to manifest.json, catalog.json, and extension.vsixmanifest, as described above.

**Comment by breadshort** [comment]
> @breadshort, what version and edition of VS are you installing it into? Add the version numbers and editions to manifest.json, catalog.json, and extension.vsixmanifest, as described above.

2017 Enterprise 15.9.20 (trial)
2019 Community 16.4.5
2019 Pro 16.4.5 (trial)
2019 Enterprise 16.4.5 (trial)

I did everything that @SteGriff described (see attached file [ObjectExporter.zip](https://github.com/OmarElabd/ObjectExporter/files/4313414/ObjectExporter.zip)
)
still can't install the extension (same error)

UPD: I think that some people don't work on my VS - I can't install the Microsoft Code Analysis extension either. I'll find out why.

UPD2: Solved. The problem was because of the wrong version of vsixinstaller.exe.

**Comment by x123-design** [comment]
@SteGriff thanks for the tips but I double click the ObjectExplorer.vsix file I get:

Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: This VSIX package is invalid because it does not contain the file extension.vsixmanifest at the root. The VSIX file may be corrupted.

The extension.vsixmanifest file is there though.

After doing the edits you suggest, I zip the folder, I rename to ObjectExplorer.vsix

Thanks

**Comment by breadshort** [comment]
@gustier 
> After doing the edits you suggest, I zip the folder, I rename to ObjectExplorer.vsix

You should not archive a folder, but the contents of a folder.

**Comment by x123-design** [comment]
@breadshort
Ah, right, makes sense.
I dragged them out of the zip and edited and dragged back - seemed to install ok
Thanks

**Comment by x123-design** [comment]
@breadshort
Ok, I have checked the extension is enabled which it is. 
However, when I hit a breakpoint I expect to see the 'Export Objects' in the menu. 
Any ideas how to get the exporter window?

**Comment by x123-design** [comment]
@breadshort - in VS 2019

**Comment by breadshort** [comment]
@gustier
> Any ideas how to get the exporter window?

Main menu -> Tools -> Export Objects

![look](https://raw.githubusercontent.com/OmarElabd/ObjectExporter/master/ObjectExporter.VsPackage/Documentation/Object%20Exporter%20-%20Tools%20Menu.png)

**Comment by x123-design** [comment]
@breadshort 
Yes, been using ctrl+E, ctrl+O, as no menu in VS 2019.

The Object Exporter is proving very buggy.  

@anyone, Is there a commercial product that does this which supports newer versions of .net?

**Comment by SteGriff** [comment]
As mentioned earlier in the thread, it's worth looking at ObjectDumper.NET, I found its output to be better, but you do need to write some code (not very difficult): https://www.nuget.org/packages/ObjectDumper.NET/

**Comment by x123-design** [comment]
Nice, Thanks

**Comment by bigloudjeff** [comment]
I am not affiliated with this product in any way other than being a customer. But I find [OzCode ](https://oz-code.com/debugging-redefined/)to be useful and it has an almost identical object exporting feature.
https://oz-code.com/debugging-redefined/

**Comment by dharmaturtle** [comment]
I actually prefer ObjectDumper.net these days because I use a program called NCrunch that makes it simple to see the console output of tests. I have an extension method `.D()` that takes the object it's attached to and feeds it to ObjectDumper.net, which then prints it to the console. Makes me want to write tests now, as compared to being forced to do it. Unfortunately, NCrunch is not free, nor am I aware of another program/plugin that makes it simple to see a test's console output. 

![image](https://user-images.githubusercontent.com/1278803/76639429-1ab85880-651c-11ea-968e-1ad17b8e3d89.png)

I made a small repo [here](https://github.com/dharmaturtle/objectdumptofile) that demonstrates how you can "dump" the console to a file. When combined with an autoupdating text editor like VS Code, the experience is somewhat better. Somewhat =\ If someone could figure out how to execute the "Repeat last run" command twice in a row, that would be great.

Edit: Aaaand I figured it out. To execute "Repeat last run" repeatedly, make a change in your code, save, and then try to run it again. I guess VS is trying to save you from running the same test over and over.

**Comment by tahir-khalid** [comment]
> I am not affiliated with this product in any way other than being a customer. But I find [OzCode ](https://oz-code.com/debugging-redefined/)to be useful and it has an almost identical object exporting feature.
> https://oz-code.com/debugging-redefined/

Nice tool reminds me of CodeRush which I use and love.

**Comment by vurso** [comment]
Looks like the author abandoned the project so I will try and pick this up with my own fork.

**Comment by OmarElabd** [comment]
@vurso I just want to clarify that the project hasn't been abandoned and there are updates planned for the near future.

**Comment by vurso** [comment]
> 
> 
> @vurso I just want to clarify that the project hasn't been abandoned and there are updates planned for the near future.

Great to hear you're still here Omar look forward to the updates my friend.  Be safe and well. Peace

**Comment by igoyetche** [comment]
Please update it for VS2019

**Comment by redwards510** [comment]
I did the fixes suggested by @SteGriff but I still get the "dependencies cannot be resolved" error when trying to install. this is VS 2019 Pro. Hoping for a fix because Ozcode costs money!

**Comment by vurso** [comment]
Would be good to compile a list of current issues.

Personally I think my issues are to do with the version of Visual Studio
2019 in my case its Enterprise on Windows 10 LTSB so location of extensions
for example is completely not what you expect so I think once we work out
where stuff should go and someone fixes the installer should have a better
chance of working maybe?

**Comment by ldy985** [comment]
Have you tried the version I compiled a long time ago? https://github.com/OmarElabd/ObjectExporter/issues/84#issuecomment-540138520

**Comment by vreniose95** [comment]
> I compiled a version using one of the pull requests: [ObjectExporter.zip](https://github.com/OmarElabd/ObjectExporter/files/3708957/ObjectExporter.zip) it should work fine with VS2019.

Thanks a ton my man!
King

**Comment by stefan-sherwood** [comment]
Note that the [instructions on how to modify the extension to work in VS2019](https://github.com/OmarElabd/ObjectExporter/issues/84#issuecomment-595293446) left out another place to edit:

From `extension.vsixmanifest`:

```
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[14.0,17.0)" DisplayName="Visual Studio core editor" />
  </Prerequisites>

```

needs to be changed to 

```
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,17.0)" DisplayName="Visual Studio core editor" />
  </Prerequisites>

```

When I followed the linked instructions using version `[17.0,18.0)` in all 3 places (`catalog.json, manifest.json, extension.vsixmanifest`) and also changed:

  ```
<Installation InstalledByMsi="false">
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[14.0,17.0)" />
  </Installation>
```

to

```
  <Installation InstalledByMsi="false">
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0,17.0)">
       <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0,18.0)">
       <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
  </Installation>
```

in `extension.vsixmanifest`, I was able to get it to install in Visual Studio 2022. But when I run the extension I'm greeted with this message:

![image](https://user-images.githubusercontent.com/2094779/211919439-f41909ea-5e80-4f91-b948-ba9a16052376.png)
